// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACRIsKIuDJRGBzX79UNYPORwfwHf-Umvo',
    appId: '1:316603944477:web:4cc3e50e4b676d534a00f4',
    messagingSenderId: '316603944477',
    projectId: 'geminis-aec9d',
    authDomain: 'geminis-aec9d.firebaseapp.com',
    storageBucket: 'geminis-aec9d.appspot.com',
    measurementId: 'G-YR19PL903B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB0L4MwpN6bLjEL_yPYy9o2Oxs7Z7vkp8',
    appId: '1:316603944477:android:50e12e31973044c64a00f4',
    messagingSenderId: '316603944477',
    projectId: 'geminis-aec9d',
    storageBucket: 'geminis-aec9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaLV9Icko19cMnu814Cfe8Vrzpbejpsyo',
    appId: '1:316603944477:ios:24d2c1e2ee3cb1e54a00f4',
    messagingSenderId: '316603944477',
    projectId: 'geminis-aec9d',
    storageBucket: 'geminis-aec9d.appspot.com',
    iosClientId: '316603944477-g0ld0qpr8sfrui7i054v8mj4oiale0u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectopersonal',
  );
}
